version: '3.5'

services:
  sm-db:
    container_name: sm-db
    image: kaium123/sm-db
    ports:
      - "54321:5432"
    
    volumes:
      - sm-db:/var/lib/postgresql
    environment:
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: 12345678
    networks:
      - social_media_network
    restart: unless-stopped

  social_media_redis:
    container_name: social_media_redis
    image: 'redis:7-alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    networks:
      - social_media_network
    ports:
      - '63792:6379'
  auth:  # New service
    container_name: auth
    image: kaium123/auth:2
    ports:
      - "8089:8089"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - social_media_network
    depends_on:
      - sm-db
      - social_media_redis
    restart: unless-stopped
    env_file:
      - base.env

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      - social_media_network

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - social_media_network

  promtail:
    image:  grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./grafana/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    depends_on:
      - loki
    networks:
      - social_media_network

networks:
  social_media_network:
    driver: bridge

volumes:
  sm-db: {}
  # minio_storage: {}

