version: '3.5'

services:
  sm-db:
    container_name: sm-db
    image: kaium123/sm-db
    ports:
      - "54321:5432"
    volumes:
      - sm-db:/var/lib/postgresql
    environment:
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: 12345678
    networks:
      - social_media_network
    restart: unless-stopped

  social_media_redis:
    container_name: social_media_redis
    image: 'redis:7-alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    networks:
      - social_media_network
    ports:
      - '63792:6379'
  auth:  # New service
    container_name: auth
    image: kaium123/auth:2
    ports:
      - "8089:8089"
    networks:
      - social_media_network
    depends_on:
      - sm-db
      - social_media_redis
    restart: unless-stopped
    env_file:
      - base.env

networks:
  social_media_network:
    driver: bridge

volumes:
  sm-db: {}
  # minio_storage: {}

