version: '3.5'

services:
  user_db:
    container_name: user_db
    image: postgres
    ports:
      - "54322:5432"
    volumes:
      - user_db:/var/lib/postgresql
    environment:
      POSTGRES_DB: user
      POSTGRES_PASSWORD: user_54321
    networks:
      - social_media_network
    restart: unless-stopped

  social_media_redis:
      container_name: social_media_redis
      image: 'redis:7-alpine'
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_PORT_NUMBER=6379
      networks:
        - social_media_network
      ports:
        - '63792:6379'

networks:
  social_media_network:
    driver: bridge

volumes:
  user_db: {}
  # minio_storage: {}

